### ISSUE TITLE
struct perf_event_attr seems to be wrong

### ISSUE THREAD

**Issue by arilou** [libbpf/libbpf-sys#30]
Hi,

Looking at the definition of perf_event_attr it seems wrong compared to what it should be
`
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct perf_event_attr {
    pub _address: u8,
}
`

Where in fact it's
```
           struct perf_event_attr {
               __u32 type;                 /* Type of event */
               __u32 size;                 /* Size of attribute structure */
               __u64 config;               /* Type-specific configuration */

               union {
                   __u64 sample_period;    /* Period of sampling */
                   __u64 sample_freq;      /* Frequency of sampling */
               };

               __u64 sample_type;  /* Specifies values included in sample */
               __u64 read_format;  /* Specifies values returned in read */

               __u64 disabled       : 1,   /* off by default */
                     inherit        : 1,   /* children inherit it */
                     pinned         : 1,   /* must always be on PMU */
                     exclusive      : 1,   /* only group on PMU */
                     exclude_user   : 1,   /* don't count user */
                     exclude_kernel : 1,   /* don't count kernel */
                     exclude_hv     : 1,   /* don't count hypervisor */
                     exclude_idle   : 1,   /* don't count when idle */
                     mmap           : 1,   /* include mmap data */
                     comm           : 1,   /* include comm data */
                     freq           : 1,   /* use freq, not period */
                     inherit_stat   : 1,   /* per task counts */
                     enable_on_exec : 1,   /* next exec enables */
                     task           : 1,   /* trace fork/exit */
                     watermark      : 1,   /* wakeup_watermark */
                     precise_ip     : 2,   /* skid constraint */
                     mmap_data      : 1,   /* non-exec mmap data */
                     sample_id_all  : 1,   /* sample_type all events */
                     exclude_host   : 1,   /* don't count in host */
                     exclude_guest  : 1,   /* don't count in guest */
                     exclude_callchain_kernel : 1,
                                           /* exclude kernel callchains */
                     exclude_callchain_user   : 1,
                                           /* exclude user callchains */
                     mmap2          :  1,  /* include mmap with inode data */
                     comm_exec      :  1,  /* flag comm events that are
                                              due to exec */
                     use_clockid    :  1,  /* use clockid for time fields */
                     context_switch :  1,  /* context switch data */
                     write_backward :  1,  /* Write ring buffer from end
                                              to beginning */
                     namespaces     :  1,  /* include namespaces data */
                     ksymbol        :  1,  /* include ksymbol events */
                     bpf_event      :  1,  /* include bpf events */
                     aux_output     :  1,  /* generate AUX records
                                              instead of events */
                     cgroup         :  1,  /* include cgroup events */
                     text_poke      :  1,  /* include text poke events */

                     __reserved_1   : 30;

               union {
                   __u32 wakeup_events;    /* wakeup every n events */
                   __u32 wakeup_watermark; /* bytes before wakeup */
               };

               __u32     bp_type;          /* breakpoint type */

               union {
                   __u64 bp_addr;          /* breakpoint address */
                   __u64 kprobe_func;      /* for perf_kprobe */
                   __u64 uprobe_path;      /* for perf_uprobe */
                   __u64 config1;          /* extension of config */
               };

               union {
                   __u64 bp_len;           /* breakpoint length */
                   __u64 kprobe_addr;      /* with kprobe_func == NULL */
                   __u64 probe_offset;     /* for perf_[k,u]probe */
                   __u64 config2;          /* extension of config1 */
               };
               __u64 branch_sample_type;   /* enum perf_branch_sample_type */
               __u64 sample_regs_user;     /* user regs to dump on samples */
               __u32 sample_stack_user;    /* size of stack to dump on
                                              samples */
               __s32 clockid;              /* clock to use for time fields */
               __u64 sample_regs_intr;     /* regs to dump on samples */
               __u32 aux_watermark;        /* aux bytes before wakeup */
               __u16 sample_max_stack;     /* max frames in callchain */
               __u16 __reserved_2;         /* align to u64 */

           };
```

**Comment by arilou** [comment]
If it helps here some FFI someone wrote
https://docs.rs/perf/0.0.0/src/perf/ffi.rs.html

Also it seems like redbpf old sys module had it as well
https://docs.rs/redbpf/0.9.8/redbpf/sys/perf/struct.perf_event_attr.html

**Comment by arilou** [comment]
It seems like what's is missing is in bindings.h
#include <linux/perf_event.h>

But not sure how you want to solve this for __LIBBPF_SYS_NOVENDOR

**Comment by anakryiko** [comment]
libbpf is coming with its own set of Linux UAPI headers (in https://github.com/libbpf/libbpf/tree/master/include/uapi/linux). perf_event.h is not there, but we can add it there (and keep it in sync automatically). Will that help with SYS_NOVENDOR? @alexforster do you use libbpf's UAPI headers or rely on system ones?

**Comment by arilou** [comment]
While we are at it, I suggest we will also add
```
struct perf_sample_raw {
	struct perf_event_header header;
	uint32_t size;
	char data[];
};

struct perf_sample_lost {
	struct perf_event_header header;
	uint64_t id;
	uint64_t lost;
	uint64_t sample_id;
};

enum perf_event_type {
	PERF_RECORD_MMAP = 1,
	PERF_RECORD_LOST = 2,
	PERF_RECORD_COMM = 3,
	PERF_RECORD_EXIT = 4,
	PERF_RECORD_THROTTLE = 5,
	PERF_RECORD_UNTHROTTLE = 6,
	PERF_RECORD_FORK = 7,
	PERF_RECORD_READ = 8,
	PERF_RECORD_SAMPLE = 9,
	PERF_RECORD_MMAP2 = 10,
	PERF_RECORD_AUX = 11,
	PERF_RECORD_ITRACE_START = 12,
	PERF_RECORD_LOST_SAMPLES = 13,
	PERF_RECORD_SWITCH = 14,
	PERF_RECORD_SWITCH_CPU_WIDE = 15,
	PERF_RECORD_NAMESPACES = 16,
	PERF_RECORD_KSYMBOL = 17,
	PERF_RECORD_BPF_EVENT = 18,
	PERF_RECORD_CGROUP = 19,
	PERF_RECORD_TEXT_POKE = 20,
	PERF_RECORD_MAX = 21,
};
```

So one can use can use **perf_buffer__new_raw** and define a different algorithm for fetching i.e for batching

**Comment by anakryiko** [comment]
sgtm

**Comment by alexforster** [comment]
> libbpf is coming with its own set of Linux UAPI headers (in https://github.com/libbpf/libbpf/tree/master/include/uapi/linux). perf_event.h is not there, but we can add it there (and keep it in sync automatically).

This would be my preference. That way, if we ever go back to generating these bindings on user machines, users won't need to have Linux headers installed (same as with libbpf).

> Will that help with SYS_NOVENDOR? @alexforster do you use libbpf's UAPI headers or rely on system ones?

Both – https://github.com/libbpf/libbpf-sys/blob/c1850cc107ea43ae9a103167d207ac5a770e5a5d/bindings.h#L1-L13

When "novendor" is unset, we rely entirely on libbpf's copy of UAPI headers. When it is set, we rely on the headers from the local machine.

**Comment by anakryiko** [comment]
> > libbpf is coming with its own set of Linux UAPI headers (in https://github.com/libbpf/libbpf/tree/master/include/uapi/linux). perf_event.h is not there, but we can add it there (and keep it in sync automatically).
> 
> This would be my preference. That way, if we ever go back to generating these bindings on user machines, users won't need to have Linux headers installed (same as with libbpf).

Done in https://github.com/libbpf/libbpf/pull/445.

**Comment by alexforster** [comment]
Cool – any chance a new release is coming soon?

**Comment by anakryiko** [comment]
In a week or two, most probably. Still waiting for few more deprecation patches landing before cutting v0.7.

**Comment by arilou** [comment]
Any ETA when the next release will be?

**Comment by anakryiko** [comment]
@arilou, libbpf v0.7.0 was cut 10 days ago (https://github.com/libbpf/libbpf/releases/tag/v0.7.0).

@alexforster can you please create a new libbpf-sys release?

**Comment by alexforster** [comment]
I gave it a try last week and I ran into an issue. For some reason, `bindgen` is now generating duplicate definitions of `BTF_KIND_*` preprocessor defines.

Example:

```
    --> src/bindings.rs:3157:1
     |
220  | pub const BTF_KIND_TYPE_TAG: u32 = 18;
     | -------------------------------------- previous definition of the value `BTF_KIND_TYPE_TAG` here
...
3157 | pub const BTF_KIND_TYPE_TAG: ::std::os::raw::c_uint = 18;
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `BTF_KIND_TYPE_TAG` redefined here
     |
```

I'm not sure why, but I'll continue digging.

**Comment by anakryiko** [comment]
It's this, probably: https://github.com/libbpf/libbpf/blob/master/src/btf.h#L385-L398

Not sure on how to work around this, but this is done intentionally for systems with older UAPI headers.

**Comment by alexforster** [comment]
cc @mdaverde

**Comment by alexforster** [comment]
@arilou Can you check this out and see if it works for you?

https://github.com/libbpf/libbpf-sys/pull/37

`struct perf_sample_raw` and `struct perf_sample_lost` aren't defined anywhere in `libbpf` or `uapi`. The only place they're defined is [here](https://github.com/torvalds/linux/blob/169e77764adc041b1dacba84ea90516a895d43b2/tools/lib/bpf/libbpf.c#L11445-L11456), which bindgen can't see. However, we are now generating `struct perf_event_header` which should be enough for this use case, I think.

**Comment by arilou** [comment]
Thanks you @alexforster, it looks good, I understand *perf_sample_raw* and *perf_sample_lost* are currently not defined in the header files so bindgen cannot access them, but I was hoping that it makes more sense to move them to a header file, so once can implement there own drain mechanism.

I dont mind defining those structs manually for myself, as they wont change, but I figured it would make more sense to export them,

**Comment by alexforster** [comment]
That sounds like a reasonable request, but since it's a change to the C API, I'll defer to @anakryiko

**Comment by anakryiko** [comment]
`perf_sample_raw` and `perf_sample_lost` are internal to libbpf, it's not part of any kind of UAPI. It corresponds to the way that perf subsystem lays out the data in perf buffer, but it's just a custom struct. So there is no need for libbpf to expose it as an API. Just define your own struct with the same layout.

**Comment by arilou** [comment]
Hi @anakryiko , thank you for the fast reply, I understand it's not a UAPI but libbpf exports today:
perf_buffer__new_raw
in which you can define an event_cb

I was under the assumption that the way you should work with the event_cp:
is something like
switch (e->type) {
case PERF_RECORD_SAMPLE:
     perf_sample_raw *sample = (perf_sample_raw *)e;
     ...
     break;
case PERF_RECORD_LOST:
    perf_sample_lost *sample = (perf_sample_lost *)e;
    ....
    break;
}

was there a different idea of how to use this API?

**Comment by anakryiko** [comment]
yes, but for perf_buffer__new_raw() user is expected to define their own data structure (or just not use any structure at all, just fetch necessary bytes). `raw` part means "advanced use case and user knows how to deal with it". So yeah, just go ahead and define your types, nothing wrong with that.

Also, I haven't double check and I haven't looked into that code for a while, the layout of that perf sample will depend on exact set of flags you specify when you call perf_event_open() syscall. So there is no single perf_sample_raw that would work for all cases.

**Comment by arilou** [comment]
thanks @anakryiko , will do that
