### ISSUE TITLE
Add a feature to statically link elfutils and zlib

### ISSUE THREAD

**Issue by javierhonduco** [libbpf/libbpf-sys#40]
👋 Hi folks! First of all, thanks so much for this crate! 

I am trying to create a statically linked binary, [rbperf](https://github.com/javierhonduco/rbperf/),  that depends on `libbpf-rs`.

The first thing I bumped into was that while libbpf is linked statically, elfutils and zlib aren't. With this patch to add this feature in libbpf-sys (https://github.com/javierhonduco/libbpf-sys/commit/4a6b36794c05129f1ca16d23f6e708bb39f9a266) and exposing it in libbpf-rs (https://github.com/javierhonduco/libbpf-rs/commit/b66a96e6214cbb79e87fc17296ee4c1d66d6c5db) I am able to depend on fewer dynamic libraries, and getting a bit closer to the fully static goal.

**Before**
```
[javierhonduco@computer-2 rbperf]$ ldd target/debug/rbperf
	linux-vdso.so.1 (0x00007ffca76d3000)
	libelf.so.1 => /lib/libelf.so.1 (0x00007fbfb7f5a000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fbfb7f40000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fbfb7f20000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fbfb7e42000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fbfb7c41000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fbfb87cf000)
```

**After**
```
[javierhonduco@computer rbperf]$ ldd target/debug/rbperf
	linux-vdso.so.1 (0x00007ffde392c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f6dd42ff000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f6dd4221000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f6dd4020000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6dd4ba0000)
```

Would you be open to the idea of having this implemented? If so, I would be more than happy to open a PR 😄

**Comment by anakryiko** [comment]
I wonder if it's better and cleaner to add this as an option for libbpf Makefile itself?

**Comment by alexforster** [comment]
I'm fine with this change in general (and I don't have a particular opinion on whether it belongs in Rust or in C). However, I do want to express my desire to default to dynamic linking, due to the license of `libelf` (LGPL).

**Comment by alexforster** [comment]
Done in https://crates.io/crates/libbpf-sys/0.8.1+v0.8.0
