### ISSUE TITLE
Incorrect libbpf submodule published to crates.io for version 1.0.2+v1.0.1

### ISSUE THREAD

**Issue by masmullin2000** [libbpf/libbpf-sys#46]
The version of libbpf published to crates.io is version 1.0.0 not 1.0.1

Steps to reproduce:
$ mkdir download_area
$ cd download_area
$ curl -L https://crates.io/api/v1/crates/libbpf-sys/1.0.2+v1.0.1/download --output libbpf-sys.tar.gz
$ tar xzvf libbpf-sys.tar.gz
$ cat libbpf-sys-1.0.2+v1.0.1/libbpf/src/Makefile | grep LIBBPF_PATCH_VERSION

Expected Result:
LIBBPF_PATCH_VERSION := 1

Actual Result
LIBBPF_PATCH_VERSION := 0

NOTES:

Observe that in libbpf.h the change described here: https://github.com/libbpf/libbpf/commit/5847387048653f35dac74bf98e9e9fc65c08c202 
is not available.

Because libbpf is at version 1.0.0, but the bindings.rs was generated for version 1.0.1 the bpf_object_open_opts structure is incorrect.

**Comment by alexforster** [comment]
Oh crap, fixing now...

**Comment by alexforster** [comment]
Published `1.0.3+v1.0.1` and yanked .2 – sorry about that!

**Comment by danielocfb** [comment]
Sorry, I am not able to follow. What happened and what changed that fixed anything? I am seeing a [single commit](https://github.com/libbpf/libbpf-sys/commit/8e6455dff3b189e06b26f9f5c1040b1c336a4684) that bumps the crate's version again, without any other visible changes.

**Comment by alexforster** [comment]
Sorry, I should have elaborated. Yep, you got it exactly – I forgot `git submodule update --init --recursive` before running `cargo publish`.

**Comment by jirutka** [comment]
> I forgot git submodule update --init --recursive before running cargo publish.

That’s why it’s better to always publish crates from CI.

**Comment by danielocfb** [comment]
> > I forgot git submodule update --init --recursive before running cargo publish.
> 
> That’s why it’s better to always publish crates from CI.

Interesting; and to be honest, I had not heard of that being done before. Do you have a pointer to a setup that does that? Not that I think it's particularly difficult to get done, just curious to see the approach (and lazy...).
