### ISSUE TITLE
Show example to build

### ISSUE THREAD

**Issue by nurdann** [libbpf/libbpf-sys#51]
Recently, I was trying out building `libbpf-rs` ran into https://github.com/libbpf/libbpf-rs/issues/300 

I think it would be nice to show which system packages need to be installed, e.g. on Ubuntu
```
sudo apt install libelf-dev pkgconf
```
where `pkgconf` provides `pkg-config` executable.

**Comment by alexforster** [comment]
Sure. In the readme, I do [mention](https://github.com/libbpf/libbpf-sys/blob/master/README.md#building) its dependencies a few times, but there's no harm in adding explicit examples.
