### ISSUE TITLE
Test that `libbpf-rs` compiles without error in CI

### ISSUE THREAD

**Issue by alexforster** [libbpf/libbpf-sys#53]
Right now, there are no tests beyond ensuring that `libbpf_set_print` can be called. This ensures that something hasn't gone horribly wrong, but it doesn't do much to prevent API breakage.

In libbpf/libbpf-rs#303, a minor release of `libbpf-sys` broke `libbpf-rs` because `bindgen`'s default behavior changed. This would have been prevented if we somehow tested compiling `libbpf-rs` in CI, but I don't know enough about GitHub CI to implement that.

**Comment by danielocfb** [comment]
I was going to suggest doing just that, but then it struck me as too `libbpf-rs` centric for me to propose here :-) Glad you suggested this step.
