### ISSUE TITLE
Clarification on the metadata in semvar version

### ISSUE THREAD

**Issue by yihuaf** [libbpf/libbpf-sys#58]
Hi, I want to ask about the metadata in the semvar version since it produces the warning:

>version requirement `1.1.1+v1.0.1` for dependency `libbpf-sys` includes semver metadata which will be ignored, removing the metadata is recommended to avoid confusion

If I understand this correctly, the `+v1.0.1` is for information only to indicate to a human reader which libbpf version is used from upstream. Therefore, if needed, we can safely remove the metadata version from cargo manifest?

**Comment by danielocfb** [comment]
Thanks for bringing this up. Yes, it can likely be ignored. See https://doc.rust-lang.org/cargo/reference/resolver.html#version-metadata

**Comment by yihuaf** [comment]
> Thanks for bringing this up. Yes, it can likely be ignored. See https://doc.rust-lang.org/cargo/reference/resolver.html#version-metadata

Thank you!
