### ISSUE TITLE
Enable Static aarch64 compilation in the CI

### ISSUE THREAD

**Issue by mmullin-halcyon** [libbpf/libbpf-sys#68]
CI exists for aarch64, however the author of the recent static changes (aka me) did not update the CI to run a build aarch64 with static.

This led to a required hotfix (https://github.com/libbpf/libbpf-sys/commit/c043865bc069c886b5ac1f87a62d2c2a48f3ce70)

I will start work on this tomorrow evening.

**Comment by alexforster** [comment]
Thanks, no rush.

**Comment by mmullin-halcyon** [comment]
I don't think this is possible without github providing ARM based builders.  I've tried various builders which would normally --build-- the software, however inside of libelf, there is a "check for ability to run" (IE they compile a test binary and try to run it... which of course fails).

Closing this ticket
